Repository codestates-seb/seb39_main_025, pull requests merged in 2022-09, with the labels that each got.

#31 feat: 회원가입, 로그인 요청 로직 구현, jwt 토큰 로컬스토리지에 저장 로직 임시구현
  client/.eslintrc.json
  client/build/asset-manifest.json
  client/build/favicon.ico
  client/build/index.html
  client/build/logo192.png
  client/build/logo512.png
  client/build/manifest.json
  client/build/robots.txt
  client/build/static/js/main.012a9398.js
  client/build/static/js/main.012a9398.js.LICENSE.txt
  client/build/static/js/main.012a9398.js.map
  client/package.json
  client/src/components/Form/user/LoginForm.js
  client/src/index.js
  client/src/redux/store/store.js
  client/src/redux/userSlice.js
Labels: FE - 김현호, 로직

#32 first setting
  .gitignore
Labels: BE - 김지환, BE - 김용빈

#35 design:SNS 단건 게시글 스타일 컴포넌트 작업 [유저 프로필&아이디, 업로드 이미지, 게시글, 좋아요, 댓글,더보기 버튼]
  client/src/GlobalStyle.js
  client/src/assets/comment.png
  client/src/assets/more.png
  client/src/components/Nav/NavTop.js
  client/src/components/SNS/SingleFeed/SigleFeedContent.js
  client/src/components/SNS/SingleFeed/SingleFeed.js
  client/src/components/SNS/SingleFeed/SingleFeedContentStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedImage.js
  client/src/components/SNS/SingleFeed/SingleFeedImageStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedTopBar.js
  client/src/components/SNS/SingleFeed/SingleFeedTopBarStyle.js
  client/src/pages/HomePage.js
Labels: FE - 송슬기, 스타일링

#40 feat: 로그인 회원가입 구현
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/generated/com/main/mapper/MemberMapperImpl.java
  src/main/java/com/main/ProjectApplication.java
  src/main/java/com/main/config/CorsConfig.java
  src/main/java/com/main/config/SecurityConfig.java
  src/main/java/com/main/config/SwaggerConfig.java
  src/main/java/com/main/config/auth/PrincipalDetails.java
  src/main/java/com/main/config/auth/PrincipalDetailsService.java
  src/main/java/com/main/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/main/config/jwt/JwtAuthorizationFilter.java
  src/main/java/com/main/domain/member/Member.java
  src/main/java/com/main/domain/member/MemberRepository.java
  src/main/java/com/main/dto/auth/MemberRegisterDto.java
  src/main/java/com/main/dto/auth/MemberResponseDto.java
  src/main/java/com/main/exception/BusinessLogicException.java
  src/main/java/com/main/exception/ErrorResponse.java
  src/main/java/com/main/exception/ExceptionCode.java
  src/main/java/com/main/exception/GlobalExceptionAdvice.java
  src/main/java/com/main/mapper/MemberMapper.java
  src/main/java/com/main/service/member/MemberService.java
  src/main/java/com/main/web/controller/member/MemberController.java
  src/test/java/com/main/ProjectApplicationTests.java
Labels: BE - 김지환, BE - 김용빈, 로직

#41 design:단건 게시글 컴포넌트 스타일 완료...ellipsis 완료... 좋아요 버튼...댓글보기...코멘트 달기... …
  client/package-lock.json
  client/package.json
  client/src/components/Footer/Footer.js
  client/src/components/Footer/FooterStyle.js
  client/src/components/Nav/NavBottomStyle.js
  client/src/components/Nav/NavTopStyle.js
  client/src/components/SNS/SingleFeed/SigleFeedContent.js
  client/src/components/SNS/SingleFeed/SingleFeedContentStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedImage.js
  client/src/components/SNS/SingleFeed/SingleFeedImageStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleFeedReplies.js
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleFeedReply.js
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleReedReplyStyle.js
Labels: FE - 송슬기, 스타일링

#42 feat: sns 게시글 업로드 입력폼 구현
  client/build/asset-manifest.json
  client/build/index.html
  client/build/static/js/main.012a9398.js
  client/build/static/js/main.012a9398.js.map
  client/build/static/js/main.b25178b9.js
  client/build/static/js/main.b25178b9.js.LICENSE.txt
  client/build/static/js/main.b25178b9.js.map
  client/package-lock.json
  client/package.json
  client/src/components/Aside/Aside.js
  client/src/components/Aside/AsideStyle.js
  client/src/components/Form/sns/SnsFormStyles.js
  client/src/components/Form/sns/SnsUploadForm.js
  client/src/components/Form/user/LoginForm.js
  client/src/pages/HomePage.js
  client/src/pages/SingleFeedPage.js
  client/src/redux/userSlice.js
Labels: FE - 김현호

#43 add: gradlewrapper.jar추가
  gradle/wrapper/gradle-wrapper.jar
Labels: BE - 김지환

#45 eat: sns 업로드 폼 모달창 구현 완료, aside 버튼 별도 컴포넌트로 분리 완료
  client/package-lock.json
  client/package.json
  client/src/components/Aside/AButtons.js
  client/src/components/Aside/Aside.js
  client/src/components/Aside/AsideStyle.js
  client/src/components/Form/sns/SnsFormStyles.js
  client/src/components/Form/sns/SnsUploadForm.js
  client/src/index.js
  client/src/pages/HomePage.js
  client/src/pages/SingleFeedPage.js
Labels: FE - 김현호

#47 Dev fe 임시 더미데이터 파일 생성.. 유저 게시물 페이지..포스팅 갤러리 디자인..유저 프로필..버튼 팝업 컴포넌트 생성..npm-i 설치 요망
  client/package-lock.json
  client/package.json
  client/public/assets/comment.png
  client/public/assets/footerLogo.png
  client/public/assets/icons_search.png
  client/public/assets/left-arrow.png
  client/public/assets/logo.png
  client/public/assets/main.png
  client/public/assets/map.png
  client/public/assets/more.png
  client/public/assets/notifications.png
  client/public/assets/paw-active.png
  client/public/assets/paw.png
  client/public/assets/pet-bedge.png
  client/public/assets/right-arrow.png
  client/public/assets/shelter-bedge.png
  client/public/assets/tag.png
  client/public/assets/upload-file.png
  client/public/assets/upload.png
  client/src/App.js
  client/src/GlobalStyle.js
  client/src/assets/notifications.png
  client/src/components/SNS/PopUp/Alarm.jsx
  client/src/components/SNS/PopUp/MobileButtonDetail.jsx
  client/src/components/SNS/PopUp/PopUpStyle.js
  client/src/components/SNS/SingleFeed/SigleFeedContent.jsx
  client/src/components/SNS/SingleFeed/SingleFeed.jsx
  client/src/components/SNS/SingleFeed/SingleFeedImage.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleFeedReplies.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleFeedReply.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleReedReplyStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedTopBar.jsx
  client/src/components/SNS/SingleFeed/SingleFeedTopBarStyle.js
  client/src/components/SNS/User/MobileUserFeedTopBar.jsx
  client/src/components/SNS/User/UserFeed.jsx
  client/src/components/SNS/User/UserFeedGallery.jsx
  client/src/components/SNS/User/UserFeedProfile.jsx
  client/src/components/SNS/User/UserFeedStyle.js
  client/src/data/data.js
  client/src/pages/UserFeedPage.js
Labels: FE - 송슬기, 스타일링

#48 design:fix 모달 스타일 컴포넌트 버그 수정, data map, 유저 게시물 페이지 알림 팝업 스타일 & 함수 버그 수정
  client/src/components/Form/sns/SnsFormStyles.js
  client/src/components/Nav/NavBottomStyle.js
  client/src/components/SNS/PopUp/Alarm.jsx
  client/src/components/SNS/PopUp/PopUpStyle.js
  client/src/components/SNS/SingleFeed/SigleFeedContent.jsx
  client/src/components/SNS/SingleFeed/SingleFeed.jsx
  client/src/components/SNS/SingleFeed/SingleFeedContentStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedImageStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedTopBar.jsx
  client/src/components/SNS/User/UserFeed.jsx
  client/src/components/SNS/User/UserFeedStyle.js
  client/src/data/data.js
  client/src/pages/HomePage.js
Labels: FE - 송슬기, 스타일링, 버그수정

#53 Design: 추천 아이디 컴포넌트 생성, 단건피드와 추천 아이디 컴포넌트 무한스크롤 로직 생성,게시물 수정 버튼 모달 팝업…
  client/db.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/assets/weekly.png
  client/src/assets/weekly_white.png
  client/src/components/Aside/AButtons.js
  client/src/components/Aside/AsideStyle.js
  client/src/components/Aside/SnsAside.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Loader/EndMessage.jsx
  client/src/components/Loader/Loader.jsx
  client/src/components/Nav/NavBottom.js
  client/src/components/Nav/NavBottomStyle.js
  client/src/components/SNS/PopUp/MobileButtonDetail.jsx
  client/src/components/SNS/SingleFeed/SingleFeed.jsx
  client/src/components/SNS/SingleFeed/SingleFeedStyle.js
  client/src/components/SNS/Suggestion/SuggestInfinite.jsx
  client/src/components/SNS/Suggestion/Suggestion.jsx
  client/src/components/SNS/Suggestion/SuggestionStyle.js
  client/src/components/SNS/WeeklyRank/WeeklyRank.jsx
  client/src/components/SNS/WeeklyRank/WeeklyRankStyle.js
  client/src/pages/SingleFeedPage.js
  client/src/pages/WeeklyRankPage.js
Labels: FE - 송슬기, 스타일링

#58 fix: 모달창 프로그레스바 버그 수정
  client/src/components/SNS/Story/Modal.jsx
  client/src/components/SNS/Story/Story.jsx
Labels: FE - 김현호, 로직, 버그수정

#61 댓글 오류 수정 & 현호님 스토리 합침
  client/db.json
  client/package-lock.json
  client/package.json
  client/src/components/Form/sns/SnsUploadForm.jsx
  client/src/components/SNS/SingleFeed/SigleFeedContent.jsx
  client/src/components/SNS/SingleFeed/SingleFeed.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/RepleContent.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/RepleList.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleFeedReplies.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleFeedReply.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleReedReplyStyle.js
  client/src/components/SNS/Story/Modal.jsx
  client/src/components/SNS/Story/Stories.jsx
  client/src/components/SNS/Story/Story.jsx
  client/src/components/SNS/Story/Styles.js
  db.json
Labels: FE - 송슬기, 버그수정

#73 마이페이지 회원정보 서버 테스트 완료 & 프론트엔드 깃 컨플릭 오류 해결
  client/db.json
  client/package.json
  client/src/App.jsx
  client/src/GlobalStyle.js
  client/src/components/Form/mypage/Form.jsx
  client/src/components/Form/mypage/MyPageForm.jsx
  client/src/components/Form/mypage/MyPageFormStyles.js
  client/src/components/Form/mypage/Styles.js
  client/src/components/Form/user/LoginForm.jsx
  client/src/components/Form/user/SignupForm.jsx
  client/src/components/SNS/SingleFeed/SingleFeed.jsx
  client/src/components/SNS/SingleFeed/SingleFeedImage.jsx
  client/src/components/SNS/SingleFeed/SingleFeedImageStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedReply/RepleContent.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/RepleList.jsx
  client/src/pages/MyEditPage.jsx
  client/src/pages/MyPage.jsx
  client/src/redux/userSlice.js
Labels: FE - 송슬기, 로직, 버그수정

#77 마이페이지 강아지와, 봉사자 정보 주소검색, 어사이드 메뉴바 구현
  client/db.json
  client/package-lock.json
  client/package.json
  client/src/assets/mypage.png
  client/src/assets/mypage_2.png
  client/src/assets/mypage_3.png
  client/src/components/Footer/Footer.jsx
  client/src/components/Form/mypage/BackgrounImage.jsx
  client/src/components/Form/mypage/DaumAddress.jsx
  client/src/components/Form/mypage/MyPageForm.jsx
  client/src/components/Form/mypage/MyPageFormStyles.js
  client/src/components/Nav/AsideMenu.jsx
  client/src/components/Nav/AsideMenuStyle.js
  client/src/components/Nav/NavBottom.jsx
  client/src/components/Nav/NavBottomStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedReply/RepleContent.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleReedReplyStyle.js
  client/src/pages/HomePage.jsx
  client/src/pages/MyPage.jsx
  client/src/pages/SingleFeedPage.jsx
  db.json
  env
Labels: FE - 송슬기, 스타일링

#80 feat:좋아요버튼기능 구현,게시물삭제구현,다이렉트메세지 컴포넌트 작업중
  .github/ISSUE_TEMPLATE/BE_TASK_ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/FE_TASK_ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/development.yml
  .gitignore
  client/db.json
  client/src/App.jsx
  client/src/assets/direct-message.png
  client/src/assets/profile.png
  client/src/components/Aside/AButtons.js
  client/src/components/Form/mypage/MyPageForm.jsx
  client/src/components/Form/mypage/MyPageFormStyles.js
  client/src/components/Mypage/BackgrounImage.jsx
  client/src/components/Mypage/MypageInfo.jsx
  client/src/components/Mypage/MypageInfoStyle.js
  client/src/components/Nav/AsideMenuStyle.js
  client/src/components/SNS/DirectMessage/Chatbox.jsx
  client/src/components/SNS/DirectMessage/DirectMessage.jsx
  client/src/components/SNS/DirectMessage/DirectMessageStyle.js
  client/src/components/SNS/DirectMessage/FriendsList.jsx
  client/src/components/SNS/PopUp/MobileButtonDetail.jsx
  client/src/components/SNS/SingleFeed/SigleFeedContent.jsx
  client/src/components/SNS/SingleFeed/SingleFeed.jsx
  client/src/components/SNS/SingleFeed/SingleFeedImage.jsx
  client/src/components/SNS/SingleFeed/SingleFeedStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedTopBar.jsx
  client/src/components/SNS/Suggestion/Suggestion.jsx
  client/src/components/SNS/Suggestion/SuggestionStyle.js
  client/src/components/SNS/User/UserFeed.jsx
  client/src/components/SNS/User/UserFeedStyle.js
  client/src/pages/DirectMessagePage.jsx
  client/src/pages/HomePage.jsx
  client/src/pages/WeeklyRankPage.jsx
  db.json
Labels: FE - 송슬기, 로직, 스타일링

#81 프론트엔드 코드 병합
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.jsx
  client/src/components/Form/sns/SnsUploadForm.jsx
  client/src/components/Form/user/LoginForm.jsx
  client/src/components/Map/KakaoMap.jsx
  client/src/components/Map/Map.jsx
  client/src/components/Map/Styles.js
  client/src/components/Nav/Nav.jsx
  client/src/components/Nav/NavTop.jsx
  client/src/pages/LoginPage.jsx
  client/src/redux/store/store.js
  client/src/redux/userSlice.js
Labels: FE - 김현호, 로직, 리팩토링, 버그수정

#84 fix: 로그인, 게시글 등록 코드 수정
  client/src/components/Form/checklist/CheckList.jsx
  client/src/components/Form/sns/SnsUploadForm.jsx
  client/src/components/Form/user/LoginForm.jsx
  client/src/components/Map/adopt/AdoptContents.jsx
  client/src/components/Nav/NavTop.jsx
  client/src/components/SNS/SingleFeed/SingleFeed.jsx
  client/src/redux/store/store.js
  client/src/redux/userSlice.js
Labels: FE - 김현호, 로직, 리팩토링, 버그수정
