Repository codestates-seb/seb39_main_025, pull requests merged in 2022-10, with the labels that each got.

#95 conflict 해결, 단건 게시글 SnsEditForm에 해당 입력값 불러오기 & 댓글 입력과 삭제 백엔드와 테스트 통과된 코드 입니다
  client/src/components/Form/sns/SnsEditForm.jsx
  client/src/components/SNS/PopUp/MobileButtonDetail.jsx
  client/src/components/SNS/SingleFeed/SigleFeedContent.jsx
  client/src/components/SNS/SingleFeed/SingleFeed.jsx
  client/src/components/SNS/SingleFeed/SingleFeedImageStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedReply/RepleContent.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/RepleList.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleFeedReply.jsx
  client/src/components/SNS/SingleFeed/SingleFeedStyle.js
Labels: FE - 송슬기, 리팩토링, 버그수정

#96 프론트엔드 코드 병합
  client/public/assets/testcover.png
  client/public/index.html
  client/src/assets/testcover.png
  client/src/components/Checklist/CheckList.jsx
  client/src/components/Checklist/Styles.js
  client/src/components/Map/KakaoMap.jsx
  client/src/components/Map/SearchResultStyle.js
  client/src/components/Map/SearchResults.jsx
  client/src/components/Map/Styles.js
  client/src/components/Map/adopt/AdoptContents.jsx
  client/src/components/Map/adopt/Checklist/CheckList.jsx
  client/src/components/Map/adopt/Checklist/CheckResult.jsx
  client/src/components/Map/adopt/Checklist/CheckResultStyles.js
  client/src/components/Map/adopt/Checklist/Styles.js
  client/src/components/Map/adopt/Checklist/TestStartCover.jsx
  client/src/components/Map/adopt/Checklist/TestStartStyles.js
  client/src/components/Map/alert/AlertContents.jsx
  client/src/data/questions.js
  client/src/pages/AdoptPetPage.jsx
Labels: FE - 김현호, 로직, 스타일링, 리팩토링, 버그수정

#99 fix: 안되는 기능 컴포넌트 삭제 및 정리 좋아요기능 테스트중
  client/src/App.jsx
  client/src/components/Aside/AButtons.js
  client/src/components/Form/sns/SnsEditForm.jsx
  client/src/components/Form/user/LoginForm.jsx
  client/src/components/Mypage/BackgrounImage.jsx
  client/src/components/Nav/NavTopStyle.js
  client/src/components/SNS/DirectMessage/Chatbox.jsx
  client/src/components/SNS/DirectMessage/DirectMessage.jsx
  client/src/components/SNS/DirectMessage/DirectMessageStyle.js
  client/src/components/SNS/DirectMessage/FriendsList.jsx
  client/src/components/SNS/PopUp/Alarm.jsx
  client/src/components/SNS/PopUp/MobileButtonDetail.jsx
  client/src/components/SNS/PopUp/PopUpStyle.js
  client/src/components/SNS/SingleFeed/SigleFeedContent.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleFeedReply.jsx
  client/src/components/SNS/SingleFeed/SingleFeedReply/SingleReedReplyStyle.js
  client/src/components/SNS/SingleFeed/SingleFeedTopBar.jsx
  client/src/components/SNS/SingleFeed/SingleFeedTopBarStyle.js
  client/src/components/SNS/User/MobileUserFeedTopBar.jsx
  client/src/components/SNS/User/UserFeed.jsx
  client/src/components/SNS/User/UserFeedGallery.jsx
  client/src/components/SNS/User/UserFeedProfile.jsx
  client/src/components/SNS/User/UserFeedStyle.js
  client/src/pages/HomePage.jsx
  client/src/pages/UserFeedPage.jsx
Labels: FE - 송슬기, 스타일링, 버그수정

#100 sns loading spinner 컴포넌트 구현
  client/src/assets/loading.gif
  client/src/components/Loading/Loading.jsx
  client/src/components/Loading/LoadingStyle.js
  client/src/components/Mypage/MypageInfo.jsx
  client/src/components/SNS/SingleFeed/SingleFeed.jsx
Labels: FE - 송슬기, 로직, 스타일링

#101 랜딩페이지 구현 그리고 sns 좋아요 기능 구현
  client/package-lock.json
  client/package.json
  client/src/assets/adopt.png
  client/src/assets/alert.png
  client/src/assets/mobile.png
  client/src/assets/mobileSns.png
  client/src/components/Form/sns/SnsEditForm.jsx
  client/src/components/Landing/LandingContent.jsx
  client/src/components/Landing/ModelingStyles.js
  client/src/components/Landing/Scroll.jsx
  client/src/components/Landing/Styles.js
  client/src/components/Landing/scroll.css
  client/src/components/Loader/EndMessage.jsx
  client/src/components/Loader/Loader.jsx
  client/src/components/Loading/Loading.jsx
  client/src/components/SNS/PopUp/MobileButtonDetail.jsx
  client/src/components/SNS/SingleFeed/SigleFeedContent.jsx
  client/src/components/SNS/SingleFeed/SingleFeedStyle.js
  client/src/pages/HomePage.jsx
Labels: FE - 송슬기, 스타일링

#104 fix:userFeedPage버그수정
  client/src/App.jsx
  client/src/pages/UserFeedPage.jsx
Labels: 버그수정

#105 디자인 수정
  client/src/components/Aside/Left/Styles.js
  client/src/components/Map/Styles.js
  client/src/components/SNS/User/UserFeedStyle.js
  client/src/pages/AdoptPetPage.jsx
  client/src/pages/AlertPage.jsx
Labels: 버그수정

#109 first commit
  .gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/mainproject/mainBuddy/MainBuddyApplication.java
  server/src/main/resources/application.properties
  server/src/test/java/com/mainproject/mainBuddy/MainBuddyApplicationTests.java
Labels: BE - 김지환, BE - 김용빈

#110 add : settings
  server/build.gradle
Labels: BE - 김지환, BE - 김용빈

#111 feat: 로그인 회원가입 구현
  server/src/main/java/com/mainproject/mainBuddy/audit/Auditable.java
  server/src/main/java/com/mainproject/mainBuddy/config/auth/PrincipalDetails.java
  server/src/main/java/com/mainproject/mainBuddy/config/auth/PrincipalDetails1.java
  server/src/main/java/com/mainproject/mainBuddy/config/auth/PrincipalDetailsService.java
  server/src/main/java/com/mainproject/mainBuddy/config/filter/CorsConfig.java
  server/src/main/java/com/mainproject/mainBuddy/config/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/mainBuddy/config/filter/JwtAuthorizationFilter.java
  server/src/main/java/com/mainproject/mainBuddy/config/filter/SecurityConfig.java
  server/src/main/java/com/mainproject/mainBuddy/controller/MemberController.java
  server/src/main/java/com/mainproject/mainBuddy/domain/Member.java
  server/src/main/java/com/mainproject/mainBuddy/domain/MemberRepository.java
  server/src/main/java/com/mainproject/mainBuddy/dto/auth/MemberRegisterDto.java
  server/src/main/java/com/mainproject/mainBuddy/dto/auth/MemberResponseDto.java
  server/src/main/java/com/mainproject/mainBuddy/dto/auth/MemberUpdateDto.java
  server/src/main/java/com/mainproject/mainBuddy/dto/member/CMRespDto.java
  server/src/main/java/com/mainproject/mainBuddy/exception/BusinessLogicException.java
  server/src/main/java/com/mainproject/mainBuddy/exception/ControllerException.java
  server/src/main/java/com/mainproject/mainBuddy/exception/CustomValidationApiException.java
  server/src/main/java/com/mainproject/mainBuddy/exception/CustomValidationException.java
  server/src/main/java/com/mainproject/mainBuddy/exception/ErrorResponse.java
  server/src/main/java/com/mainproject/mainBuddy/exception/ExceptionCode.java
  server/src/main/java/com/mainproject/mainBuddy/exception/GlobalExceptionAdvice.java
  server/src/main/java/com/mainproject/mainBuddy/mapper/MemberMapper.java
  server/src/main/java/com/mainproject/mainBuddy/service/MemberService.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: BE - 김지환

#112 feat: image_upload
  server/src/main/java/com/mainproject/mainBuddy/config/auth/PrincipalDetails.java
  server/src/main/java/com/mainproject/mainBuddy/config/auth/PrincipalDetailsService.java
  server/src/main/java/com/mainproject/mainBuddy/config/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/mainBuddy/config/filter/JwtAuthorizationFilter.java
  server/src/main/java/com/mainproject/mainBuddy/config/filter/SecurityConfig.java
  server/src/main/java/com/mainproject/mainBuddy/controller/image/ImageController.java
  server/src/main/java/com/mainproject/mainBuddy/controller/member/MemberController.java
  server/src/main/java/com/mainproject/mainBuddy/domain/image/Image.java
  server/src/main/java/com/mainproject/mainBuddy/domain/image/ImageRepository.java
  server/src/main/java/com/mainproject/mainBuddy/domain/likes/Likes.java
  server/src/main/java/com/mainproject/mainBuddy/domain/likes/LikesRepository.java
  server/src/main/java/com/mainproject/mainBuddy/domain/member/Member.java
  server/src/main/java/com/mainproject/mainBuddy/domain/member/MemberRepository.java
  server/src/main/java/com/mainproject/mainBuddy/dto/auth/MemberUpdateDto.java
  server/src/main/java/com/mainproject/mainBuddy/dto/image/ImageResponseDto.java
  server/src/main/java/com/mainproject/mainBuddy/dto/image/ImageUpdateDto.java
  server/src/main/java/com/mainproject/mainBuddy/dto/image/ImageUploadDto.java
  server/src/main/java/com/mainproject/mainBuddy/dto/member/MemberProfileDto.java
  server/src/main/java/com/mainproject/mainBuddy/dto/member/MemberProfileDto2.java
  server/src/main/java/com/mainproject/mainBuddy/exception/ControllerException.java
  server/src/main/java/com/mainproject/mainBuddy/mapper/MemberMapper.java
  server/src/main/java/com/mainproject/mainBuddy/service/image/ImageService.java
  server/src/main/java/com/mainproject/mainBuddy/service/member/MemberGetService.java
  server/src/main/java/com/mainproject/mainBuddy/service/member/MemberService.java
Labels: BE - 김용빈

#113 feat: comment_api
  server/src/main/java/com/mainproject/mainBuddy/controller/comment/CommentController.java
  server/src/main/java/com/mainproject/mainBuddy/domain/comment/Comment.java
  server/src/main/java/com/mainproject/mainBuddy/domain/comment/CommentRepository.java
  server/src/main/java/com/mainproject/mainBuddy/domain/image/Image.java
  server/src/main/java/com/mainproject/mainBuddy/domain/likes/Likes.java
  server/src/main/java/com/mainproject/mainBuddy/dto/comment/CommentDto.java
  server/src/main/java/com/mainproject/mainBuddy/dto/comment/CommentResponseDto.java
  server/src/main/java/com/mainproject/mainBuddy/dto/image/ImageUploadDto.java
  server/src/main/java/com/mainproject/mainBuddy/service/commit/CommentService.java
Labels: BE - 김용빈

#114 Feat/likes
  server/src/main/java/com/mainproject/mainBuddy/MainBuddyApplication.java
  server/src/main/java/com/mainproject/mainBuddy/mapper/CommentMapper.java
  server/src/main/java/com/mainproject/mainBuddy/mapper/ImageMapper.java
  server/src/main/java/com/mainproject/mainBuddy/mapper/LikesMapper.java
  server/src/main/java/com/mainproject/mainBuddy/service/image/LikesService.java
Labels: BE - 김지환
